version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform
      - curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform_1.5.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo Initializing Terraform
      - terraform init

  build:
    commands:
      - echo Running Terraform Plan
      - terraform plan
      - echo Applying Terraform Changes
      - terraform apply -auto-approve

